FORMAT: 1A

# Mineself

Mineself is a server which collects and stores your digital footprint. Together with clients on different platform and scenario, the project would help you understand and showcase yourself better.

## GET /

+ Response 200 (application/json)
  
  Hello World
